- articles/bot-design-navigation.md
Hello everyone! I think I stumbled upon a minor typo on line 15 while reading the documentation. As these little typos are often hard to catch, I thought I'd just quickly propose this change and see if it helps.
> Fixing minor grammar error

- articles/includes/code/dotnet-formflow.cs
There should be a break-statement at the end of the default case, since it may not compile at all and can be especially confusing for newcomers to C#.
> Fix connectToFramework switch case

- articles/includes/code/dotnet-formflow-advanced.cs
Hello everyone!
After working through this chapter of the documentation I propose to expand the code-snippet of the validation function for the SandwichOrder's FormBuilder.
In the style of the other examples, there should be more surrounding code to make it easier for inexperienced readers to understand where the validation function should be added to. During my first read-through, I had to pull up and search the corresponding sample project to understand where this code should live, which was different from other parts of the documentation previously.
> expand validationFunction

- articles/dotnet/bot-builder-dotnet-add-rich-card-attachments.md
- articles/nodejs/bot-builder-nodejs-send-rich-cards.md
- articles/rest-api/bot-framework-rest-connector-add-rich-cards.md
> [RichCards] Minor Typo fix

- articles/rest-api/bot-framework-rest-connector-authentication.md
Particularly, the scope for the emulator path changes to use the appid instead of a fixed URI. I added the endpoint (which matches the connector path) for completeness as these are all of the key/values that are needed for the emulator authentication path.
> Adding endpoint & scope changes for emulator path.

- articles/channel-connect-twilio.md
convert external Twilio links to HTML style target="_blank" so they open in new tab
> convert external Twilio links to HTML style target="_blank" 

- articles/channel-connect-telegram.md
convert markdown style links to HTML style links with `target="_blank"` to open in new tab
> Telegram channel config - convert external links to open in new tab

- articles/debug-bots-cortana-skill-invoke.md
If you're debugging through Cortana, then the Microsoft App credentials need to specified in both the Bot Framework portal and the Web.config file. I also found that bots always ran on port 3979. And lastly, unless I specified the host header the requests would fail with 400.
> Secure bot reminder and ngrok command.

- articles/includes/code/dotnet-add-attachments.cs
The types of Attachment Layouts class is called AttachmentLayoutTypes and not AttachmentLayouts.
https://docs.botframework.com/en-us/csharp/builder/sdkreference/d7/d87/class_microsoft_1_1_bot_1_1_connector_1_1_attachment_layout_types.html
> Changed AttachmentLayouts to AttachmentLayoutTypes

- articles/nodejs/bot-builder-nodejs-send-suggested-actions.md
Added some documentation for the difference between `imBack` and `postBack`, as there is little documentation available for some card actions, and there have been some questions circulating online forums about usage. For example, see [this StackOverflow](https://stackoverflow.com/questions/44875959/microsoft-botframework-suggested-cards/44876518#44876518) question that I answered not that long ago.
> Addition of postBack

- articles/includes/code/node-getstarted.js
- articles/nodejs/bot-builder-nodejs-concepts.md
- articles/nodejs/bot-builder-nodejs-quickstart.md
- articles/nodejs/bot-builder-nodejs-send-suggested-actions.md
Building console bots are a quick and easy way to get up-and-running, but the examples from the old docs are not in the new docs. I think adding some code examples and language back in is appropriate. Even though most will want to use the ChatConnector because of the Bot Framework channels, console bots and the ConsoleConnector serve a good purpose for prototyping, and as potential set-up utilities on devices without (or with limited) access to the Internet.
> Added ConsoleConnector language and example

- articles/rest-api/bot-framework-rest-connector-authentication.md
Adding warnings and notes that describe the Auth v3.2 change that will come this Fall.
> Update to describe Auth change v3.2

- articles/resources-links-help.md
- articles/resources/TOC.md
- articles/troubleshoot-general-problems.md
- contributor-guide/tools-and-setup.md
This PR tweaks wording and adds guidance around the types of questions which are and are not appropriate to post on Stack Overflow. By directing users to the "How To Ask" guide before sending them to Stack Overflow, the likelihood of posting a well received, answerable question should be markedly improved.
Context for this change is described in #61.
> Add guidance around on-topic questions for Stack Overflow

- articles/nodejs/bot-builder-nodejs-message-create.md
Hi - just saw a small typo in passing.
S
> [Minor] Fix typo

- articles/dotnet/bot-builder-dotnet-dialogs.md
In bot-builder-dotnet-dialogs.md, there is a reference to `Prompts.Confirm`. However, that's a function from the Node.js version of the SDK - the C# function that's actually called in the associated code sample is `PromptDialog.Confirm`.
> Updates to bot-builder-dotnet-dialogs.md

- articles/rest-api/bot-framework-rest-direct-line-3-0-send-activity.md
Without a Content-Type header of ``application/json`` the DirectLine service returns a 500.
> Add Content-Type header in doc

- articles/channel-connect-directline.md
High-speed storage is on for all bots and the option has been removed from the config page.
> Remove high-speed storage reference

- articles/dotnet/bot-builder-dotnet-quickstart.md
Indicates that `Bot Controller.zip` and `Bot Dialog.zip` should go on the item templates folder instead of the project template folder.
Added the default route for item templates folders.
> Some templates are ItemTemplates

- articles/nodejs/bot-builder-nodejs-dialog-replace.md
As documentation is saying here: https://docs.botframework.com/en-us/node/builder/chat-reference/classes/_botbuilder_d_.dialog.html#reloadaction , reload action doesn't handle "confirmPrompt" (more details available on IBeginDialogActionOptions documentation about what is really available for reloadAction)
> Removing "confirmPrompt" on reload action

- articles/includes/code/node-getstarted.js
Per bug report - fix for https://github.com/Microsoft/BotBuilder/issues/4068
> Update env variable naming to work with post-GA bot service

- articles/rest-api/bot-framework-rest-connector-add-media-attachments.md
Here is my testing python3 code:
```python
skype_bot_data = {
"type": "message",
"text": "Hello",
"from": {
"id": "real-python-user",
"name": "Real Python User"
},
"channelId": "skype",
"conversation": {
"id": CONVERSATION_ID
},
"attachments": [
{
"contentType": "image/jpeg",
"contentUrl": "data:image/png;base64,"+recognised_file_base64_string,
"name": "file-name.jpg"
}
]
}
```
Btw, looks like it doesn't matter if contentType is proper, but it always must be set with base64 `contentUrl`
> content vs. contentUrl for attachment in base64

- articles/nodejs/bot-builder-nodejs-dialog-actions.md
There should be a comma between two key-value pairs in JSON.
> Fix syntax error

- articles/dotnet/bot-builder-dotnet-state-azure-cosmosdb.md
Fixed the class structure as earlier there were just namespaces and code without any names of class and methods.
> Updated state azure cosmos db file

- articles/bot-service-quickstart-registration.md
I believe that the application environment strings need to be modified before testing the bot.
These notations are taken from [articles/includes/snippet-tip-bot-config-settings.md](/MicrosoftDocs/bot-framework-docs/blob/live/articles/includes/snippet-tip-bot-config-settings.md) just for example.
> Adding bot modification procedure to bot registration

- articles/v4sdk/bot-builder-conversations.md
Fix grammatical error, removed superfluous "if'
> Grammatical fix to bot-builder-conversations.md

- articles/v4sdk/bot-builder-basics.md
removed duplicate words "of of"
> Update bot-builder-basics.md, remove dup words

- articles/includes/snippet-publish-to-channel.md
Fixed wrong link for skype configuration page in snippet-publish-to-channel.md
> Fixed wrong link for skype configuration page

- articles/rest-api/bot-framework-rest-connector-api-reference.md
Might already be covered in a diff PR (there are several).
`api-reference`
- fix misspelled wording for `Framework`
> Typo in docs

- articles/dotnet/bot-builder-dotnet-proactive-messages.md
Updated the code samples using this source:
https://github.com/Microsoft/BotBuilder-Samples/blob/master/CSharp/core-proactiveMessages/startNewDialog/ConversationStarter.cs
`IDialogStack` does not contain the `PollAsync()` method, so had to change this to `IDialogTask` as it is in the source code.
> Update the code samples that were not compiling

- articles/javascript/bot-builder-javascript-quickstart.md
- removed unnecessary npm init
- also removed the npm install commands that added bot fx components to the unused package.json created in the above step
- moved the NOTE about possibly requiring windows-build tools closer to the pre-reqs section.  It's my observation that on a clean Win 10, this is required in order to get c++ compilers and python 2.x installed.  these are both required for the restify component
- made the commandline for installing generator-botbuilder@perview consistent with how we issue other npm install commands
> Fix some bugs in initial bot creation steps

- articles/bot-builder-tools-az-cli.md
Changed MSBot services table to list endpoint instead of localhost, so that it matches the documentation on the MSBot README, and the actual command line switch used when connecting the service.
> Changed localhost to endpoint in the MSBot services table

- articles/v4sdk/bot-builder-howto-qna.md
Sample middleware registration was invalid with 4.0.1-preview. Modified so that sample indicates a single QnaMakerRegistration object and fixed casing on KnowledgeBaseId.
> Updated middleware registration in line with 4.0.1-preview

- articles/includes/code/dotnet-input-hints.cs
Code was not showing on Docs page as reference links where pointing to blocks that did not exist.  Example: [!code-csharpAccepting input] was looking for // <Accepting input> but in the linked code it had // <Accepting>. Update the code block reference names
> Fixed reference links to code

- articles/bot-service-manage-speech-priming.md
Customers requesting official documentation of lack of support for non US LUIS apps for speech priming feature for EU due to GDPR requirements to keep data in EU and no workaround currently available.
> Adding support statement for regional LUIS apps

- articles/v4sdk/bot-builder-howto-v4-state.md
This resolves issue #294 .
Issue resolved as part of [#Hacktoberfest](https://aka.ms/hacktoberfest) .
> Resolution for grammar issue #294

- articles/v4sdk/bot-builder-howto-qna.md
Previous command does not work. We should put one space.
> Update command to create metadata for qna maker

- contributor-guide/article-metadata.md
Missing a space behind the second # at the "usage" section. The h2 style isn't rendered.
By adding a space behind ## it renders the title as an h2.
> Wrongly used MD h2 title at "usage" section

- articles/bot-service-build-download-source-code.md
This snippet fell under a C# specific snippet, which made it unclear that it also applies to Node: 
"The `botFilePath` references the name of your bot, simply replace "yourbasicBot.bot" with your own bot name. To obtain the `botFileSecret` key, refer to [Bot File Encryption](https://aka.ms/bot-file-encryption) article on generating a key for your bot."
> Moved language-agnostic instruction

- articles/v4sdk/bot-builder-concept-dialog.md
The documentation opens with an overview and then flows right into discussing dialog lifecycle. I think adding a header would be a good to break that up and call more attention to the specific topic that is being discussed.
> Add "Dialog Lifecycle" header

- articles/bot-service-quickstart.md
As far as I know, the v4 of the C# and NodeJS SDK-s are not in preview anymore.
> Fix intro text for SDK v4

- articles/v4sdk/bot-builder-send-welcome-message.md
Minor code sample rendering fixes as well
> typo: atleast -> at least

- articles/TOC.md
Lower casing of README name results in a 404, changed to uppercase.
> Update link to samples repository

- articles/v4sdk/bot-builder-howto-v4-storage.md
I've created the issue in Bot Samples project as well along with the fix that describes issue in details. Please follow:
https://github.com/Microsoft/BotBuilder-Samples/issues/990
The issue has been already merged to master so I think it's good to reflect this in the documentation as well
> Azure blob storage calling _transcriptStore.GetTranscriptActivitiesAsync results in endless loop

- articles/nodejs/bot-builder-nodejs-samples.md
Bot Framework v3's samples was moved from master to v3-sdk-samples branch.
> Fix link to v3 sample repo

- articles/javascript/bot-builder-javascript-quickstart.md
md is not a standard bash command and will error on non-Windows OS's. mkdir works across OS environments.
> Update 'md' bash command to 'mkdir'

- articles/v4sdk/bot-builder-concept-state.md
Typo in paragraph State management
For example, when your retrieve -> For example, when you retrieve
> Fix typo in bot-builder-concept-state

- articles/v4sdk/bot-builder-basics.md
> Fixed typo in bot-builder-basics.md

- articles/rest-api/bot-framework-rest-connector-api-reference.md
- add documentation for Get Conversations, Delete Conversation Member, and Send Conversation History
- add documentation for their related objects in the schema section
- fix miscellaneous errors in the document while leaving major fixes for other commits
Fixes #1179
> Conversation operations in REST API reference

- articles/bot-builder-deploy-az-cli.md
Fixes: https://github.com/MicrosoftDocs/bot-docs/issues/1223
Reference: https://github.com/microsoft/botframework-sdk/issues/5429
Adds:
> [!NOTE] If you would like to use an existing App registration, you can use the command,
>
> ```cmd
> az bot create --kind webapp --resource-group "<name-of-resource-group>" --name "<name-of-web-app>" --appid "<existing-app-id>" --password "<existing-app-password>" --lang <Javascript|Csharp>;
> ```
in "Create an App registration" section. 
Also fixes a couple typos.
> Added note about using existing app registration

- articles/v4sdk/bot-builder-howto-proactive-message.md
The doc was referencing a sample that only existed in a PR that didn't get merged. This PR has it reference the actual sample, correctly.
> Fix trustServiceUrl sample reference

- articles/v4sdk/bot-builder-howto-v4-storage.md
Fixes https://github.com/microsoft/BotBuilder-Samples/issues/1674
Changes
```js
var dotenv = require('dotenv');
dotenv.load();
```
to
```js
const ENV_FILE = path.join(__dirname, '.env');
require('dotenv').config({ path: ENV_FILE });
```
because:
* `dotenv` package says to use `config()`, not `load()`
* this makes it in line with [our samples](https://github.com/microsoft/BotBuilder-Samples/blob/master/samples/javascript_nodejs/13.core-bot/index.js#L23)
> dotenv load to config

- articles/bot-service-overview-introduction.md
On https://docs.microsoft.com/en-gb/azure/bot-service/?view=azure-bot-service-4.0 there is a comma before "all in one place" but was missing here
> added a comma to be consistent
