- articles/dotnet/bot-builder-dotnet-formflow-formbuilder.md
Hello!
I found another small typo (duplicate "the") and thought I might as well quickly fix it.
> remove duplicate word

- articles/nodejs/bot-builder-nodejs-dialog-manage-conversation.md
Corrected typo at line 172 from **repsonse** to **response** in bot-builder-nodejs-dialog-manage-conversation.md
> Corrected typo at line 172 in bot-builder-nodejs-dialog-manage-conversation.md

- articles/cognitive-services-bot-intelligence-overview.md
> remove location control

- articles/channel-connect-facebook.md
I had to configure the Facebook app setting of "Allow API Access to App Settings" to "Yes" for the channel to work.
> Update settings for the Facebook app

- articles/channel-connect-kik.md
Update links from markdown style to HTML style with `target="_blank"` to open in new tab.
> Kik channel config - update external links to open in new tab

- articles/nodejs/bot-builder-nodejs-dialog-manage-conversation-flow.md
Fixes small grammar error in example
> Grammar correction. Whose, not Who's

- articles/dotnet/bot-builder-dotnet-create-messages.md
I have correct one wrong spelling.
> Just a little correction in spelling of visible

- articles/nodejs/bot-builder-nodejs-dialog-prompt.md
output: We sold 300 units for a total of $$9,000.
expected output: We sold 300 units for a total of $9,000.
> remove extra dollar sign

- articles/rest-api/bot-framework-rest-connector-api-reference.md
Added to address partner feedback
> Importance of serviceUrl for proactive messages

- articles/portal-register-bot.md
Current dialog looks like that.
> Bot registration dialog text

- articles/includes/code/node-send-card-buttons.js
Action.Http was updated to Action.OpenUrl in documentation
> Updated node-send-card-buttons.js to support latest documentation

- articles/rest-api/bot-framework-rest-connector-channeldata.md
> Corrected link error on page

- articles/v4sdk/bot-builder-basics.md
> Fix typo activty to activity

- articles/dotnet/bot-builder-dotnet-manage-conversation-flow.md
Added documentation on how to pass data between dialogs - example Github code referenced already demonstrates this: 
https://github.com/Microsoft/BotBuilder-Samples/blob/master/CSharp/core-BasicMultiDialog/Dialogs/RootDialog.cs
https://github.com/Microsoft/BotBuilder-Samples/blob/master/CSharp/core-BasicMultiDialog/Dialogs/AgeDialog.cs
> How to pass data between dialogs

- articles/dotnet/bot-builder-dotnet-state-azure-table-storage.md
Added mention of the Application_Start method to prevent confusion as to where to put the code.
> Clarification - where to put the code

- articles/bot-builder-tutorial-authentication.md
Fixes some naming issues related to Azure AD. (Namely, "Azure AD", instead of "AAD".)
> Fixing Azure AD wording

- articles/javascript/bot-builder-javascript-quickstart.md
According to the code, the response to the first request should be '0: You said "Hi"'.
> Fix bot reply

- articles/bot-service-manage-channels.md
> article  usage

- articles/includes/code/dotnet-input-hints.cs
Updates made to each code tag so links point to the correct code block
> Update Code Tags

- articles/dotnet/bot-builder-dotnet-state-azure-cosmosdb.md
Inserted line 74, as missing it in the global.asax.cs file causes a 404 error for customers.
> Update tutorial doc

- articles/bot-service-build-download-source-code.md
Typo in header, assuming it should be using instead of usubg
> Correcting typo

- articles/dotnet/bot-builder-dotnet-sdk-quickstart.md
Added a new line for the image
> Update image alignment in bot-builder-dotnet-sqk-quickstart.md

- articles/v4sdk/bot-builder-howto-qna.md
Just a silly typo fix, but it's in the Welcome message so I thought it worth getting it done!
> Fix typo in the Welcome message.

- articles/v4sdk/bot-builder-send-welcome-message.md
Remove a redundant character "
> Fix minor typo in C# code

- articles/v4sdk/bot-file-basics.md
Updated the spelling of information (from infomration) in the Additional resources section.
> Spelling errors

- articles/v4sdk/bot-builder-enterprise-template-create-project.md
> Updated language in enterprise bot docs

- articles/v4sdk/bot-builder-authentication.md
Information regarding emulator settings that are important for authentication to work and test locally
> Bot Emulator settings for Authentication

- articles/bot-service-channel-connect-skypeforbusiness.md
We need to clarify that the channel is in developer preview, and disambiguate feature support from support from Microsoft.
> Clarify that the channel is in developer preview

- articles/bot-builder-deploy-samples.md
update the min version of az cli which needs to be 2.0.54 on macOS
> fix min version of az cli

- articles/v4sdk/bot-builder-howto-add-media-attachments.md
In the "Send attachments" Subhead's C# section - the sentence "The `Attachments` property of the `Activity` object contains an array of `Attachment` objects that represent the media attachments and rich cards attached to the message. To add a media attachment to a message, create an `Attachment` object for the `message` activity and set the `ContentType`, `ContentUrl`, and `Name` properties" was repeated.
> Repetition of a sentence.

- articles/v4sdk/bot-builder-howto-v4-state.md
Changed the accessors to _accessors
> Fixed the code in C# section

- articles/bot-service-overview-introduction.md
The word was simply mis-spelled.
> Typo: Mis-spelled "information"

- articles/nodejs/bot-builder-nodejs-cortana-skill.md
Removed reference(s) to retry prompts; Cortana does not support them.
> fix for bug 1575903

- articles/v4sdk/bot-builder-virtual-assistant-introduction.md
Just a few minor update suggestions.
> Suggested updates to bot-builder-virtual-assistant-introduction.md

- articles/v4sdk/bot-builder-howto-add-media-attachments.md
* Guide users to the new drag-drop Designer 
* Update the nuget pacakge name to the correct name
> Update adaptive cards section with latest guidance

- articles/bot-service-manage-channels.md
"Connect a bot to channels" said that Skype is pre-configured, when only Web Chat should be pre-configured now
> Fix incorrect information

- articles/bot-service-concept-intelligence.md
Microsoft Cognitive Services lets  -> Microsoft Cognitive Services let
> Fix typo bot-service-concept-intelligence

- dotnet/xml/Microsoft.Bot.Builder/MessageFactory.xml
"text to speak" not "test to speak"
> Fix typo at the top of of MessageFactory.xml

- articles/bot-service-troubleshoot-general-problems.md
- articles/v4sdk/bot-builder-telemetry.md
- contributor-guide/tools-and-setup.md
> fix: MD039/no-space-in-links

- articles/nodejs/bot-builder-nodejs-recognize-intent-luis.md
Spaces inside emphasis markers
> fix: MD037/no-space-in-emphasis

- articles/bot-service-review-guidelines.md
- articles/dotnet/bot-builder-dotnet-audio-calls.md
Multiple spaces after hash on atx style heading
> fix: MD019/no-multiple-space-atx

- articles/bot-service-channels-reference.md
Derived from https://github.com/Microsoft/botbuilder-dotnet/blob/master/libraries/Microsoft.Bot.Builder.Dialogs/Choices/Channel.cs
> Add Card Action and Suggested Action Support by Channel

- articles/v4sdk/skill-implement-consumer.md
The pull request is created from live637177450100230208 to live to fix git push error for protected CLA branch
> Fix git push error for protected CLA branch
